### ISSUE TITLE
[FEATURE] 메인 배너 영역 작업

### ISSUE THREAD

**Issue by Juhee-Hwang** [LikeLion-FE-JS-Project19/marketKarly#1]
# 🌳 작업 브랜치
``

# 📝 TASK 개요
메인 페이지 마크업

# ✅ To Do 및 진행상황
- [x] 메인 배너 마크업
- [x] 메인 배너 CSS
- [x] 메인 배너 swiper
