### ISSUE TITLE
[FEATURE] main 영역 작업

### ISSUE THREAD

**Issue by Juhee-Hwang** [LikeLion-FE-JS-Project19/marketKarly#26]
# 🌳 작업 브랜치
`feature/#26`

# 📝 TASK 개요
메인 페이지 마크업

# ✅ To Do 및 진행상황
- [x] 상품 캐로셀 마크업
- [x] 상품 캐로셀 CSS
- [ ] 상품 캐로셀 클릭 시 제품 상세페이지로 이동
