### ISSUE TITLE
[BUG] merge 후 놓친 부분 수정

### ISSUE THREAD

**Issue by kyungseob7** [LikeLion-FE-JS-Project19/marketKarly#45]
## 🌳  작업 브랜치 

bug/#45

## 🐛 BUG 개요 

부주의

## ✅ TODO 및 진행현황 

- [x] 사진 경로 다시 설정
- [x] 메인 모달 z-index : 9999 설정
- [x] 사이드 바 배경색 white 설정
- [x] 사이드 바 z-index : 999 설정

## 🚧 BUG 리포트 

PR 후 머지할 때 섬세하게 보지않았다.
신중하게 PR 하겠습니다.
