### ISSUE TITLE
[BUG] 파일 경로 수정

### ISSUE THREAD

**Issue by kyungseob7** [LikeLion-FE-JS-Project19/marketKarly#50]
## 🌳  작업 브랜치 

bug/#50

## 🐛 BUG 개요 

파일경로로 인한 이미지 깨짐현상

## ✅ TODO 및 진행현황 

- [x] index.html 상단바 close.svg 경로수정
- [x] 메인캐러셀 장바구니 담기 경로수정
- [x] html 파일들에 top-bar , common.js 추가, main.js 삭제

## 🚧 BUG 리포트 

절대경로를 사용해서 제 컴퓨터에만 보였습니다. (다시 경로 수정)
svg 파일 위치 변경
