### ISSUE TITLE
[BUG] footer 리팩토링2

### ISSUE THREAD

**Issue by no-support** [LikeLion-FE-JS-Project19/marketKarly#70]
## 🌳  작업 브랜치 
`bug/#70`

## 🐛 BUG 개요 
 - 푸터 이미지 못 불러오는 문제 해결
 - 모든 html 파일 내 footer 태그 삭제 및 common.js에서 dom 생성 및 렌더링
 -  개발자 도구 콘솔 탭 에러 해결

## ✅ TODO 및 진행현황 
- [x] 푸터 이미지 못 불러오는 문제 해결
- [x] 모든 html 파일 내 footer 태그 삭제 및 common.js에서 dom 생성 및 렌더링
- [x] 개발자 도구 콘솔 탭 에러 해결

## 🚧 BUG 리포트 
- 라이브 서버에서 구동 시 url에 client가 추가되어 경로 참조를 못 하는 것이 원인이었음.
- 이미지를 못 불러올 시 alt속성값을 렌더링하는데, 글자수가 많아 마크업 레이아웃도 깨지는 문제가 있었음. -> 이미지를 못 불러와도 덩달아 레이아웃도 깨지지 않도록 비율 지정.
