### ISSUE TITLE
[REFACTORING] 리팩토링

### ISSUE THREAD

**Issue by senasoon** [LikeLion-FE-JS-Project19/marketKarly#82]
# 🌳 작업 브랜치
`refactor/#82`

# 📝 TASK 개요
lighthouse 성능 검사 결과를 참고해서 개선 사항들 수정했습니다.

# ✅ To Do 및 진행상황
- [x] html 불필요한 script 파일 제거
- [x] 배너 이미지 최적화
- [x] img width, height 설정
- [x] header a href 수정
